# Generated by Django 5.2.1 on 2026-03-23 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Gesendet'), ('accepted', 'Angenommen')], default='draft', max_length=10)),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='offers/')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatbot.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_at_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('offer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='chatbot.offerrequest')),
            ],
        ),
    ]
